export const ProductsData = [
    {
        category: 'Vegetables',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2024/01/veg_5.png',
        name: 'green pea',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Organic Green Pea Seed',
        rating: '4.3',
    },
    {
        category: 'Vegetables',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2024/01/veg_4.png',
        name: 'Lettuce',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Fresh Lettuce',
        rating: '4.3',
    },
    {
        category: 'Vegetables',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/veg_2s.png',
        name: 'Potatoes',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Russet Idaho Potatoes Fresh Premium Fruit and Produce Vegetables, 4 pound case',
        rating: '4.1',
    },
    {
        category: 'Vegetables',
        url: 'https://pngimg.com/uploads/carrot/carrot_PNG4994.png',
        name: 'Carrot',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Fresh Carrot Direct form farm',
        rating: '3.8',
    },
    {
        category: 'Vegetables',
        url: 'https://freepngimg.com/thumb/tomato/6-2-tomato-high-quality-png.png',
        name: 'Tomato',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Fresh Red Tomato',
        rating: '4.3',
    },
    {
        category: 'Vegetables',
        url: 'https://pngimg.com/uploads/pepper/pepper_PNG99172.png',
        name: 'Bell Paper',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Bell Paper',
        rating: '5.0',
    },
    {
        category: 'Vegetables',
        url: 'https://pngimg.com/uploads/cucumber/cucumber_PNG12617.png',
        name: 'Cucumber',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Fresh Cucumber',
        rating: '5.0',
    },
    {
        category: 'Desserts',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/sweet_7.png',
        name: 'Greek Gods',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'The Greek Gods Probiotic Plain Traditional Greek Yogurt, 32 oz',
        rating: '3.5',
    },
    {
        category: 'Desserts',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/sweet_1.png',
        name: 'Oui',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Oui by Yoplait Mocha & Chocolate Whole Milk Yogurt, French Style Yogurt Snack, 5 OZ Glass Yogurt Jar',
        rating: '4.0',
    },
    {
        category: 'Desserts',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/sweet_4.png',
        name: 'Go-GURT',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Simply Go-GURT Strawberry and Mixed Berry Kids Low Fat Yogurt Variety Pack, Gluten Free, 2 oz. Yogurt Tubes (16 Count)',
        rating: '5.0',
    },
    {
        category: 'Desserts',
        url: 'https://pngimg.com/uploads/cake/cake_PNG13087.png',
        name: 'Pastry',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Chocolate Pastry',
        rating: '5.0',
    },
    {
        category: 'Desserts',
        url: 'https://pngimg.com/uploads/ice_cream/ice_cream_PNG98143.png',
        name: 'Ice cream',
        size_options: ["4pk", "10pk"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'chocolate cone Ice-cream',
        rating: '4.5',
    },
    {
        category: 'Desserts',
        url: 'https://static.vecteezy.com/system/resources/previews/047/826/211/non_2x/raspberry-pudding-alone-against-transparent-background-free-png.png',
        name: 'Raspberry pudding',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Raspberry pudding',
        rating: '4.0',
    },
    {
        category: 'Fruits',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/fruit_4.png',
        name: 'Mango',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: '100% Premium Quality Garden Fresh Mango',
        rating: '5.0',
    },
    {
        category: 'Fruits',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/fruit_1s.png',
        name: 'Pineapple',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Exquisite Pineapple Creations for a Burst of Sweet Sunshine in Every',
        rating: '5.0',
    },
    {
        category: 'Fruits',
        url: 'https://purepng.com/public/uploads/large/purepng.com-bananafruitsyellowfruit-981524754330lspp8.png',
        name: 'Banana',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Perfectly Ripe Banana',
        rating: '3.4',
    },
    {
        category: 'Fruits',
        url: 'https://static.vecteezy.com/system/resources/previews/029/200/216/non_2x/watermelon-transparent-background-free-png.png',
        name: 'Watermelon',
        size_options: ["1kg", "2kg"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Fresh Watermelon',
        rating: '4.0',
    },
    {
        category: 'Fruits',
        url: 'https://pngimg.com/uploads/avocado/avocado_PNG15485.png',
        name: 'Avocado',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Avocado',
        rating: '4.8',
    },
    {
        category: 'Fruits',
        url: 'https://pngimg.com/uploads/blueberries/blueberries_PNG22.png',
        name: 'Blueberry',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Fresh blueberry',
        rating: '5.0',
    },
    {
        category: 'Beverage',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/beverage_2.png',
        name: 'G Zero',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Gatorade G Zero Sugar Thirst Quencher Sports Drink, Variety Pack, 12 fl oz, 18 Pack Bottles',
        rating: '2.5',
    },
    {
        category: 'Beverage',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/beverage_1.png',
        name: 'Mirinda',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Mirinda Orange No Artificial Flavors Soft Drink, Can, 250 Ml',
        rating: '4.5',
    },
    {
        category: 'Drinks & Juice',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/juice_5.png',
        name: 'A&W',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Diet A&W Root Beer, 12 fl oz – 12 Cans pack',
        rating: '3.5',
    },
    {
        category: 'Drinks & Juice',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/juice_3s.png',
        name: 'Apple Juice',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Great Value No Added Sweeteners 100% Apple Juice, 64 Fl. Oz.',
        rating: '5.0',
    },
    {
        category: 'Fish & Meats',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/fish_3.png',
        name: 'Tilapia Skinless',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Tilapia Skinless Fillets Value Pack, 2 lb (Frozen), Responsibly Sourced, Phosphate Free',
        rating: '4.7',
    },
    {
        category: 'Fish & Meats',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/meat_2.png',
        name: 'Chicken Breast',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Fresh Brand – Chicken Breast Tenderloins, 100% Natural, Boneless Skinless, 1.5 lb',
        rating: '4.0',
    },
    {
        category: 'Pets & Animals',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2024/01/pet_4.png',
        name: 'Lives',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Lives Paté Favorites Variety Pack Wet Cat Food, 5.5-Ounce Cans, 12-Count',
        rating: '4.8',
    },
    {
        category: 'Toys',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2024/01/toys_2.png',
        name: 'Toy Car',
        size_options: ["M"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Toy Car Gifts for Boys Girls Kids 3+, RC Cars, Remote Control Car',
        rating: '5.0',
    },
    {
        category: 'Toys',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2024/01/toys_1s.png',
        name: 'Puppy',
        size_options: ["M", "S"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Baby & Toddler Toy Smart Stages Puppy With White Shirt, For Ages 6+ Months',
        rating: '5.0',
    },
    {
        category: 'Grocery',
        url: 'https://www.radiustheme.com/demo/wordpress/themes/zilly/wp-content/uploads/2023/11/milk_2.png',
        name: 'Aptamil Gold',
        size_options: ["100gm", "500gm"],
        price_range: "$3.00 - $8.00",
        discount: "-77%",
        tag: 'Aptamil Gold Infant Formula Milk Powder for Babies - Stage 1 (Upto 6 months)',
        rating: '3.8',
    },
];

export const RestaurantData = [
    {
        category: 'Indian',
        url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a8/11/be/interior.jpg?w=600&h=-1&s=1',
        name: 'Masal Darwar',
        discount: "20%",
        tag: 'Masal Darwar, Grate indian food',
        rating: '4.5',
    },
    {
        category: 'Indian',
        url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a8/11/be/interior.jpg?w=600&h=-1&s=1',
        name: 'Masal Darwar',
        discount: "15%",
        tag: 'Masal Darwar, Grate indian food',
        rating: '4.5',
    },
    {
        category: 'Indian',
        url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a8/11/be/interior.jpg?w=600&h=-1&s=1',
        name: 'Masal Darwar',
        discount: "15%",
        tag: 'Masal Darwar, Grate indian food',
        rating: '4.5',
    },
    {
        category: 'Indian',
        url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a8/11/be/interior.jpg?w=600&h=-1&s=1',
        name: 'Masal Darwar',
        discount: "22%",
        tag: 'Masal Darwar, Grate indian food',
        rating: '4.5',
    },
    {
        category: 'Indian',
        url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a8/11/be/interior.jpg?w=600&h=-1&s=1',
        name: 'Masal Darwar',
        discount: "30%",
        tag: 'Masal Darwar, Grate indian food',
        rating: '4.5',
    },
    {
        category: 'Indian',
        url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a8/11/be/interior.jpg?w=600&h=-1&s=1',
        name: 'Masal Darwar',
        discount: "27%",
        tag: 'Masal Darwar, Grate indian food',
        rating: '4.5',
    },
    {
        category: 'Indian',
        url: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/a8/11/be/interior.jpg?w=600&h=-1&s=1',
        name: 'Masal Darwar',
        discount: "30%",
        tag: 'Masal Darwar, Grate indian food',
        rating: '4.5',
    },
];